steps:
  - group: "🔧 Autofix"
    key: "autofix"
    depends_on: []
    steps:
      - label: "Run autofix"
        command: ".buildkite/scripts/autofix.sh"
        key: "autofix-run"
        branches: "!main"
        timeout_in_minutes: 10

  - group: "🧪 Tests"
    key: "tests"
    depends_on: []
    steps:
      - label: "RSpec Tests ({{matrix}})"
        command: ".buildkite/scripts/rspec.sh"
        key: "rspec"
        matrix:
          - "0"
          - "1"
        env:
          CI_NODE_TOTAL: 2
          CI_NODE_INDEX: "{{matrix}}"
          RAILS_ENV: test
          RUBY_YJIT_ENABLE: 1
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: flexile_test
          POSTGRES_HOST: localhost
          REDIS_URL: redis://localhost:6379
        timeout_in_minutes: 20

      - label: "Playwright E2E Tests"
        command: ".buildkite/scripts/playwright.sh"
        key: "playwright"
        env:
          NODE_ENV: test
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: flexile_test
          POSTGRES_HOST: localhost
          REDIS_URL: redis://localhost:6379
        timeout_in_minutes: 30
        artifact_paths:
          - "playwright-report/**/*"

env:
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "{{ buildkite.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}"
  STRIPE_SECRET_KEY: "{{ buildkite.env.STRIPE_SECRET_KEY }}"
  WISE_API_KEY: "{{ buildkite.env.WISE_API_KEY }}"
  WISE_PROFILE_ID: "{{ buildkite.env.WISE_PROFILE_ID }}"
  KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC: "{{ buildkite.env.KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC }}"
  KNAPSACK_PRO_LOG_LEVEL: info